### PR TITLE
Minor cleanup and KCacheGrind friendlier naming

### PR DESCRIPTION
**Pull request by schleyfox**
Last year, we at Airbnb started encountering problems that required serious profiling work.  Luckily, `ruby-prof` was there to help.  While using it, we iterated on internal patches to get the results we desired.  The time has come to offer these up in the hopes that they may be useful to others.
### This PR

This is the first patchset in the series and is the base on which we built the other patches.  This fixes a few bugs we encountered with GC, enables C99 support, begins making some changes to MethodInfo that will come into play later, and tweaks the way methods are named for callgrind output.

KCacheGrind is designed for C++ and many of its features expect C++ style names.  Faking Ruby names into C++ allows the class groupings to work, for instance.  This requires `Foo::Bar#baz` to be rendered as `Foo/Bar::baz` and `Foo::Bar.baz` to become `Foo/Bar::^baz`.  
### The Other PRs

The other patches work around some issues we experienced with some of our more pathological code and work around some performance issues in post processing.  We're working to have profiles for basically everything all the time.  We're taking profiles of our app as part of our deploy system, so the faster we can get the results, the faster they can be used to verify behavior.

The next patch (https://github.com/ruby-prof/ruby-prof/pull/201) moves the detection of recursive calls into the profiler where we already have the appropriate context.  This avoids iterating recursively over call_infos in ruby, which was causing us to overflow the ruby stack.  This also avoids transforming the lightweight call_info structs into full ruby objects.

After that, we have a patch (https://github.com/ruby-prof/ruby-prof/pull/202) that optimizes method elimination by allowing the set of exclusions to be set prior to the start of the profiling, which allows exclusions to be computed efficiently while the profiler is running.  It also includes a set of exclusions that we found to be rather helpful.  We make heavy use of method elimination because we weren't having a great time making sense of:

Hash#each party

From there, we implemented a FastCallTreePrinter in C to cut down on the printing time and avoid turning the C structs into Ruby objects.  We also expanded calling contexts in the output to display recursion in an easier way for us to understand.  This produces acyclic calling context graphs.  We initially implemented the acyclic calling context in Ruby, so we can also show that to better explain what's going on.  I'll push out a PR for this once we've made some determinations around the recursion detection and method elimination.

We also have a Flame Graph printer implementation that may be of interest.  It's a bit more WIP, though we have been using it effectively internally.

We've been running thousands of profiles a day with these patches on our application code for the last several months.
### Performance

The big motivator was performance.  Here's the output of a partial benchmark of our application with different patches and configurations applied.

```
# No Profiler

Ran startup_1 in 25.7534
Ran health_check_1 in 0.5909
Ran api_request_1 in 1.0071
Ran api_request_2 in 0.1663
Ran api_request_3 in 0.1612
Ran web_request_1 in 0.8406
Ran web_request_2 in 0.3331
Ran web_request_3 in 0.3355
       34.95 real        29.39 user         4.83 sys

# Normal ruby-prof, no method elimination

Ran startup_1 in 39.0779
CallTree Printed startup_1 in 38.8305
Ran health_check_1 in 2.1724
CallTree Printed health_check_1 in 0.6217
Ran api_request_1 in 1.6901
CallTree Printed api_request_1 in 6.2656
Ran api_request_2 in 0.3136
CallTree Printed api_request_2 in 3.124
Ran api_request_3 in 0.3034
CallTree Printed api_request_3 in 3.0616
Ran web_request_1 in 1.7542
CallTree Printed web_request_1 in 8.9981
Ran web_request_2 in 0.727
CallTree Printed web_request_2 in 6.5484
Ran web_request_3 in 0.7873
CallTree Printed web_request_3 in 5.6912
      136.02 real       106.00 user        24.43 sys

# Normal ruby-prof, with method elimination

Ran startup_1 in 39.977
Eliminated methods in 29.710811853408813
CallTree Printed startup_1 in 23.4058
Ran health_check_1 in 1.9614
Eliminated methods in 0.9827449321746826
CallTree Printed health_check_1 in 0.371
Ran api_request_1 in 1.3887
Eliminated methods in 39.2588369846344
CallTree Printed api_request_1 in 3.5249
Ran api_request_2 in 0.29
Eliminated methods in 34.2704701423645
CallTree Printed api_request_2 in 2.0726
Ran api_request_3 in 0.326
Eliminated methods in 33.48537802696228
CallTree Printed api_request_3 in 2.5554
Ran web_request_1 in 1.3403
Eliminated methods in 35.51815676689148
CallTree Printed web_request_1 in 4.0794
Ran web_request_2 in 0.6563
Eliminated methods in 33.51047492027283
CallTree Printed web_request_2 in 4.1163
Ran web_request_3 in 0.5773
Eliminated methods in 33.727806091308594
CallTree Printed web_request_3 in 3.2598
      346.48 real       322.53 user        19.25 sys

# Patched with C Recursion Detection and C Method Elimination

Ran startup_1 in 34.5836
CallTree Printed startup_1 in 24.0047
Ran health_check_1 in 1.9761
CallTree Printed health_check_1 in 0.3595
Ran api_request_1 in 1.3652
CallTree Printed api_request_1 in 3.5098
Ran api_request_2 in 0.2698
CallTree Printed api_request_2 in 2.0452
Ran api_request_3 in 0.2682
CallTree Printed api_request_3 in 1.8847
Ran web_request_1 in 1.2476
CallTree Printed web_request_1 in 4.6494
Ran web_request_2 in 0.5839
CallTree Printed web_request_2 in 3.6305
Ran web_request_3 in 0.5609
CallTree Printed web_request_3 in 3.4074
       93.21 real        75.97 user        16.14 sys

# C Recursion, C Method Elimination, C FastCallTreePrinter

Ran startup_1 in 36.4022
CallTree Printed startup_1 in 3.4704
Ran health_check_1 in 1.9085
CallTree Printed health_check_1 in 0.1856
Ran api_request_1 in 1.3112
CallTree Printed api_request_1 in 1.543
Ran api_request_2 in 0.2723
CallTree Printed api_request_2 in 1.0085
Ran api_request_3 in 0.2515
CallTree Printed api_request_3 in 1.0083
Ran web_request_1 in 1.2896
CallTree Printed web_request_1 in 2.423
Ran web_request_2 in 0.5969
CallTree Printed web_request_2 in 2.0827
Ran web_request_3 in 0.5692
CallTree Printed web_request_3 in 1.9563
       62.98 real        55.99 user         5.84 sys
```

/cc @skaes @nelgau

### CODE REVIEW

**Comment by skaes** [comment]
This looks like it's going to be a fantastic improvement! Will have a more detailed look as soon as I can find the time.

Thx a lot for this contribution.

**Comment by schleyfox** [comment]
Gentle reminder about these PRs.  Let me know if I can help with anything.

**Comment by skaes** [comment]
@schleyfox I'm afraid I won't get around to study the pull requests before Christmas. Really sorry.

BTW, would you be interested to become a ruby-prof maintainer?

**Comment by schleyfox** [comment]
@skaes no problem, I'll probably push up a bit more of our internal fork to our github fork.

Yeah, I'd be happy to help out and maintain this project.

**Comment by rdp** [comment]
Newer MSVC does.  Do we even supports MSVC builds? ("typical" windows is
mingw which is gcc so does I think...) FWIW.

**Comment by cfis** [comment]
Yes, windows builds are almost always done using gcc hosted on mingw.  It is possible to build Ruby using VC++, but then that gets quite difficult building all the standard unix libaries that extensions depends on (zlib, libxml, iconv, etc).  As far as I know no one does that (I used to because VC++ has a lot better debugger, so is helpful in writing extensions like ruby-prof).

So I think this is fine.

**Comment by rattrayalex-stripe** [comment]
> We also have a Flame Graph printer implementation that may be of interest. It's a bit more WIP, though we have been using it effectively internally.

Hello from Stripe – yes, that'd be handy if you're able to share it! I know there's https://github.com/oozou/ruby-prof-flamegraph, but we'd rather not run a separate gem for this.

**Pull request merged**
