### PR TITLE
Test build on new Ruby versions

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by pravi** [comment]
This actually causes 2 failures and 1 error with ruby 2.5. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888192 for details.

**Comment by pravi** [comment]
Only 0.16.2 was failing with 2.5, current version (0.17.0) is passing.

**Comment by nicolasleger** [comment]
See https://bugs.ruby-lang.org/issues/13761
> "%0.0f%%" (double %) instead

**Comment by pravi** [comment]
Thanks for the pointer. Anyway I'm updating debian package to 0.17.

**Comment by cfis** [comment]
Thanks!

**Pull request merged**
