### PR TITLE
Text editor URI

### PR DESCRIPTION
**Pull request by sashaegorov**
Hi. Now it's possible to use with any text editor. By default, it works as sane as before.

### CODE REVIEW

**Comment by dgynn** [comment]
What do you think about making that an argument to the options rather than an environment variable?

Also, could this check get moved to the print method and be done once during setup rather than on every call to `link`?

**Comment by sashaegorov** [comment]
Hi, Thanks for tips

> What do you think about making that an argument to the options rather than an environment variable?

This is a pretty good idea, so I've implemented configuration via `printer` option. However, imagine a situation where there are many people working on a project. These people may use different editors. So if use option for that purpose it will be tracked be VCS and it will affect every single person who will use this code. E.g. you set up this option as `{editor_uri: :mvim}`, people who uses Emacs will be unhappy… :) So I've kept ability to override this behaviour by an environment variable, because everybody may configure profiler's output according preference *without* touching the code...

> Also, could this check get moved to the print method and be done once during setup rather than on every call to link?

Sorry, for very poor implementation. Already done. This few next commits moved editor option/environment variable/platform determination to AbstractPrinter. So this functionality is now shared across all printers. Following printers using this functionality:
- CallStackPrinter
- GraphHtmlPrinter
- FlatPrinterWithLineNumbers (for terminals such iTerm2, they able to parse URL)... now I just click to my profile output in terminal and get opened file. Awesome!

editor_link

**Comment by dgynn** [comment]
That looks pretty good to me. :+1:

**Comment by skaes** [comment]
Thx for your contribution.

**Pull request merged**
